<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\file\FileInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function purge_queuer_file_urls_file_insert(EntityInterface $entity) {
  purge_queuer_file_urls_invalidate_file($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function purge_queuer_file_urls_file_update(EntityInterface $entity) {
  purge_queuer_file_urls_invalidate_file($entity->original);
  purge_queuer_file_urls_invalidate_file($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function purge_queuer_file_urls_file_delete(EntityInterface $entity) {
  purge_queuer_file_urls_invalidate_file($entity);
}

/**
 * Implements hook_image_style_flush().
 */
function purge_queuer_file_urls_image_style_flush($style, $path = NULL) {
  $queuers = \Drupal::service('purge.queuers');
  $queuer = $queuers->get('imagestyles');
  if ($queuer) {
    $factory = \Drupal::service('purge_queuer_file_urls.url_expression_factory');
    $expressions = $factory->generateFromStyle($style, $path ?? '');
    purge_queuer_file_urls_queue_style_expressions($expressions);
  }
}

/**
 * Invalidate the given file entity.
 *
 * @param  \Drupal\file\FileInterface $file
 *   An entity to check for files to invalidate.
 */
function purge_queuer_file_urls_invalidate_file(FileInterface $file) {
  $queuers = \Drupal::service('purge.queuers');
  $queuer = $queuers->get('file');
  if ($queuer) {
    $factory = \Drupal::service('purge_queuer_file_urls.url_expression_factory');
    $expressions = $factory->generateFromFile($file);
    purge_queuer_file_urls_queue_file_expressions($expressions);
  }
}

/**
 * Queue the given file expressions for invalidation.
 *
 * @param Generator<\Drupal\purge_queuer_file_urls\UrlExpressionInterface> $expression
 *   A generator that yields expressions to invalidate.
 */
function purge_queuer_file_urls_queue_file_expressions(iterable $expressions) {
  $queuer = \Drupal::service('purge_queuer_file_urls.file_url_queuer');
  $queuer->invalidateUrls($expressions);
}

/**
 * Queue the given image style expressions for invalidation.
 *
 * @param Generator<\Drupal\purge_queuer_file_urls\UrlExpressionInterface> $expression
 *   A generator that yields expressions to invalidate.
 */
function purge_queuer_file_urls_queue_style_expressions(iterable $expressions) {
  $queuer = \Drupal::service('purge_queuer_file_urls.image_style_url_queuer');
  $queuer->invalidateUrls($expressions);
}
