<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_update().
 */
function purge_queuer_file_urls_entity_update(EntityInterface $entity) {
  $file_url_collector = \Drupal::service('purge_queuer_file_urls.file_url_collector');
  $image_style_url_collector = \Drupal::service('purge_queuer_file_urls.image_style_url_collector');
  $url_queuer = \Drupal::service('purge_queuer_file_urls.url_queuer');
  $url_queuer->invalidateUrls($file_url_collector->collect($entity));
  $url_queuer->invalidateUrls($image_style_url_collector->collect($entity));
}

/**
 * Implements hook_image_style_flush().
 */
function purge_queuer_file_urls_image_style_flush($style, $path = NULL) {
  $url_expression_factory = \Drupal::service('purge_queuer_file_urls.url_expression_factory');
  $expression = $url_expression_factory->generateFromStyle($style, $path ?? '');
  $file_urls_queuer->invalidateUrls([$expression]);
}
